### ISSUE TITLE
About data

### ISSUE THREAD

**Issue by JH-Yin** [facebookresearch/DCI#12]
I am very interested in your work, but after downloading the data, I only have 7805 JSON files in the annotations folder. However, the dataset size mentioned in the paper is 8012. What is the reason for this. Looking forward to your answer

**Comment by bordesf** [comment]
Thank you. So, the arxiv version is not up-to-date, we will update it with the conference camera ready version of our work very soon. The correct number of annotations is indeed 7805. Sorry for the inconvenience.
