### ISSUE TITLE
what LLM prompt do you use when summarising long captions?

### ISSUE THREAD

**Issue by YiguoHe** [facebookresearch/DCI#14]
Hello, I would like to know what specific prompt and related strategies you use when using LLM for summarization. Thank you very much!

**Comment by JackUrb** [comment]
All of our prompts are available [here](https://github.com/facebookresearch/DCI/blob/main/reproduction/crowdsourcing/prepare/remote_language_model.py), as well as in Appendix A of [the paper](https://arxiv.org/pdf/2312.08578).
