### ISSUE TITLE
403 access denied

### ISSUE THREAD

**Issue by Lyken17** [facebookresearch/DCI#5]
Hi authors,

Thanks for sharing the great work. I would like to try DCI but notice some file urls are no longer avaliable 

https://dl.fbaipublicfiles.com/densely_captioned_images/dci_pick1.tar.gz

https://dl.fbaipublicfiles.com/densely_captioned_images/dci.tar.gz

Could you help fix the issue?

**Comment by zhangmozhe** [comment]
The same issue

**Comment by bordesf** [comment]
Hi everyone, sorry for that, should be fixed now.
