### ISSUE TITLE
Image Ids Don't Match

### ISSUE THREAD

**Issue by zanussbaum** [facebookresearch/DCI#7]
Hi all! Thanks for the great paper and repo!

I'm trying to download and take a look at some of the images in the SAM dataset that correspond to the captions you all released, however I'm seeing some disagreement in the file names between the captions and what I get from SA-1B

The images I download from SA-1B `sa_000138.tar` seem to start with filenames similar to `sa_1543967` while the captions seem to be much different
```python
>>> paths[:5]
[PosixPath('captions/densely_captioned_images/annotations/112956-data.json'), PosixPath('captions/densely_captioned_images/annotations/112957-data.json'), PosixPath('captions/densely_captioned_images/annotations/112958-data.json'), PosixPath('captions/densely_captioned_images/annotations/112959-data.json'), PosixPath('captions/densely_captioned_images/annotations/112960-data.json')]
>>> paths[-5:]
[PosixPath('captions/densely_captioned_images/annotations/123575-data.json'), PosixPath('captions/densely_captioned_images/annotations/123576-data.json'), PosixPath('captions/densely_captioned_images/annotations/123577-data.json'), PosixPath('captions/densely_captioned_images/annotations/123578-data.json'), PosixPath('captions/densely_captioned_images/annotations/123579-data.json')]
```
I've tried downloading other tars as well but I don't seem to be able to get the correct files. Additionally, I get an error when downloading saying the checksums don't match.

Is there a different tar I should be downloading?

**Comment by bordesf** [comment]
Hi @zanussbaum, so this is the correct tar. There are no correspondance between the filenames! 
If you want to get the correct image ID from the json file, you need to open it with a text editor and look at the "image" field. This is where the image file names are stored.

**Comment by zanussbaum** [comment]
OH! *facepalm* thanks for clarifying. I was looking at the json in the extracted images and was confused why they weren't aligning :D
